# Site settings
title: Meghana Potta
description: Computational Neuroscience
website: https://meghanapotta.com
permalink: date

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: true
resume_name: Meghana Potta
resume_title: Computational Neuroscience
resume_header_intro: <p>Hi! I am a visiting student at MIT's <a href=\"https://bcs.mit.edu/\">Brain and Cognitive Sciences</a>, where I build neural network models of the brain, supervised by <a href=\"https://mcgovern.mit.edu/profile/guangyu-robert-yang/\">Robert Yang</a>. I hope to understand cognitive algorithms, specifically decision-making, using statistical machine learning methods applied to neural data.</p><p>I recently secured my Master's at the <a href=\"https://www.ini.uzh.ch/en.html\">Institute of Neuroinformatics</a> at ETH Zürich & University of Zürich. Supervised by <a href=\"https://www.ini.uzh.ch/en/research/groups/grewe.html\">Benjamin Grewe</a>, I looked at how frequently and faithfully gradient-based methods used to train recurrent neural networks discover exact ground-truth dynamics.</p><p>Previously, I spent two years building cloud infrastructure with Azure at Microsoft after a Bachelor's in Information Technology from <a href=\"https://www.nitk.ac.in/\">NITK, Surathkal</a>.</p>

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       false
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_papers:          false
resume_section_posters:         false
resume_section_software:        false
resume_section_teaching:        false
resume_section_talks:           false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_email:                 ""
  resume_github_url:            https://github.com/mpotta
  # resume_scholar_url:           ""
  resume_twitter_url:           https://twitter.com/mepotta
#   resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  resume_linkedin_url:          https://www.linkedin.com/in/mpotta/
  # resume_instagram_url:         ""
  # resume_website_url:           ""
#   resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
